"""adding foto and tipe on admin table

Revision ID: 13048f7435be
Revises: 662a3648d0da
Create Date: 2021-07-11 09:15:14.483902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13048f7435be'
down_revision = '662a3648d0da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin', sa.Column('foto_admin', sa.String(length=250), nullable=False))
    op.add_column('admin', sa.Column('tipe_admin', sa.BigInteger(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admin', 'tipe_admin')
    op.drop_column('admin', 'foto_admin')
    # ### end Alembic commands ###
