"""tugas akhir table created

Revision ID: 2426bc86cfe5
Revises: 681737b7ceb1
Create Date: 2021-06-27 19:45:27.656111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2426bc86cfe5'
down_revision = '681737b7ceb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tugasakhir',
    sa.Column('id_tugasakhir', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('judul_tugasakhir', sa.String(length=250), nullable=False),
    sa.Column('tanggal_tugasakhir', sa.Date(), nullable=False),
    sa.Column('status_tugasakhir', sa.Enum('SELESAI', 'BELUMSELESAI'), nullable=False),
    sa.Column('id_mahasiswa', sa.BigInteger(), nullable=True),
    sa.Column('id_dosen', sa.BigInteger(), nullable=True),
    sa.Column('id_prodi', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_dosen'], ['dosen.id_dosen'], ),
    sa.ForeignKeyConstraint(['id_mahasiswa'], ['mahasiswa.id_mahasiswa'], ),
    sa.ForeignKeyConstraint(['id_prodi'], ['prodi.id_prodi'], ),
    sa.PrimaryKeyConstraint('id_tugasakhir')
    )
    op.create_index(op.f('ix_tugasakhir_judul_tugasakhir'), 'tugasakhir', ['judul_tugasakhir'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tugasakhir_judul_tugasakhir'), table_name='tugasakhir')
    op.drop_table('tugasakhir')
    # ### end Alembic commands ###
