"""remove tipe on admin table

Revision ID: 33a5068318b1
Revises: 13048f7435be
Create Date: 2021-07-11 09:50:38.370628

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '33a5068318b1'
down_revision = '13048f7435be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admin', 'tipe_admin')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin', sa.Column('tipe_admin', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
