"""create prodi table

Revision ID: 361de8390c60
Revises: 55e13b565dea
Create Date: 2021-06-27 17:20:25.073678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '361de8390c60'
down_revision = '55e13b565dea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prodi',
    sa.Column('id_prodi', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('kode_prodi', sa.String(length=250), nullable=False),
    sa.Column('nama_prodi', sa.String(length=250), nullable=False),
    sa.Column('id_fakultas', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_fakultas'], ['fakultas.id_fakultas'], ),
    sa.PrimaryKeyConstraint('id_prodi')
    )
    op.create_index(op.f('ix_prodi_kode_prodi'), 'prodi', ['kode_prodi'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prodi_kode_prodi'), table_name='prodi')
    op.drop_table('prodi')
    # ### end Alembic commands ###
