"""adding if fakultas field on mahasiswa table

Revision ID: 475710da29a6
Revises: 48acb6a7f06b
Create Date: 2021-06-28 09:43:20.385295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '475710da29a6'
down_revision = '48acb6a7f06b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mahasiswa', sa.Column('id_fakultas', sa.BigInteger(), nullable=True))
    op.create_foreign_key(None, 'mahasiswa', 'fakultas', ['id_fakultas'], ['id_fakultas'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'mahasiswa', type_='foreignkey')
    op.drop_column('mahasiswa', 'id_fakultas')
    # ### end Alembic commands ###
