"""adding id fakultas field into tugas akhir table

Revision ID: 48acb6a7f06b
Revises: 2426bc86cfe5
Create Date: 2021-06-28 09:19:58.857054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48acb6a7f06b'
down_revision = '2426bc86cfe5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tugasakhir', sa.Column('id_fakultas', sa.BigInteger(), nullable=True))
    op.create_foreign_key(None, 'tugasakhir', 'fakultas', ['id_fakultas'], ['id_fakultas'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tugasakhir', type_='foreignkey')
    op.drop_column('tugasakhir', 'id_fakultas')
    # ### end Alembic commands ###
