"""adding field id fakultas on dosen table

Revision ID: 54155df4c6cd
Revises: 475710da29a6
Create Date: 2021-06-28 09:52:02.950820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54155df4c6cd'
down_revision = '475710da29a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dosen', sa.Column('id_fakultas', sa.BigInteger(), nullable=True))
    op.create_foreign_key(None, 'dosen', 'fakultas', ['id_fakultas'], ['id_fakultas'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'dosen', type_='foreignkey')
    op.drop_column('dosen', 'id_fakultas')
    # ### end Alembic commands ###
