"""tugas akhir table created

Revision ID: 681737b7ceb1
Revises: b12c7e1c8975
Create Date: 2021-06-27 19:37:54.629678

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '681737b7ceb1'
down_revision = 'b12c7e1c8975'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mahasiswa', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.drop_column('mahasiswa', 'reated_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mahasiswa', sa.Column('reated_at', mysql.DATETIME(), nullable=True))
    op.drop_column('mahasiswa', 'created_at')
    # ### end Alembic commands ###
