"""created admin table

Revision ID: e8356e7ebccc
Revises: 
Create Date: 2021-06-27 16:45:26.864803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8356e7ebccc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id_admin', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('username_admin', sa.String(length=250), nullable=False),
    sa.Column('password_admin', sa.String(length=250), nullable=False),
    sa.Column('nama_admin', sa.String(length=250), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id_admin')
    )
    op.create_index(op.f('ix_admin_username_admin'), 'admin', ['username_admin'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_admin_username_admin'), table_name='admin')
    op.drop_table('admin')
    # ### end Alembic commands ###
